<a href="https://colab.research.google.com/github/Yalla-Krishnaveni/2216123_AIML_Bootcamp/blob/main/Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/drive/MyDrive/SMSSpamCollection',sep='\t',header=None,names=["Label","Message"])


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df.head()

Label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Label    5572 non-null   object
 1   Message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [ ]:
df.shape

(5572, 2)

In [ ]:
df.isnull().sum()

Label      0
Message    0
dtype: int64

In [ ]:
#Data processing
#Method-1:Label Encoder
#Method-2
df['Label']=df.Label.map({'ham':0,'spam':1})

In [ ]:
df.head()

Label                                            Message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#Bag of Words (BoW) - sklearn library
#CountVectorizer
document=['Hello,how are you!',
   'Win money,win from home.',
   'Call me now.']
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()

In [ ]:
#fit_transform ,transform
count_vector.fit(document)

CountVectorizer()

In [ ]:
n=count_vector.get_feature_names()
n

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['are',
 'call',
 'from',
 'hello',
 'home',
 'how',
 'me',
 'money',
 'now',
 'win',
 'you']

In [ ]:
doc_array=count_vector.transform(document).toarray()
doc_array

array([[1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0]])

In [ ]:
#Converting array into a dataframe 
f_table=pd.DataFrame(data=doc_array,columns=n)
f_table

are  call  from  hello  home  how  me  money  now  win  you
0    1     0     0      1     0    1   0      0    0    0    1
1    0     0     1      0     1    0   0      1    0    2    0
2    0     1     0      0     0    0   1      0    1    0    0

In [ ]:
#Load the data
X=df.iloc[:,-1:].values
Y=df.iloc[:,:-1].values

#Method-2
#x=np.array(df[['Message']])
#y=np.array(df[['Label']])

In [ ]:
X

array([['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'],
       ['Ok lar... Joking wif u oni...'],
       ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"],
       ...,
       ['Pity, * was in mood for that. So...any other suggestions?'],
       ["The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"],
       ['Rofl. Its true to its name']], dtype=object)

In [ ]:
Y

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
#Splitting the data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1,shuffle=True)

In [ ]:
X_train.shape

(4457, 1)

In [ ]:
X_test.shape

(1115, 1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()
#Transform the Training data into freqq vectors and return the matrix
training_data=count_vector.fit_transform(X_train.flatten())
#Transform the Testing data into freq vectors and return the matrix
testing_data=count_vector.transform(X_test.flatten())

In [ ]:
from sklearn.linear_model import LogisticRegression
a=LogisticRegression()
a.fit(training_data,Y_train)
y_pred=a.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",a.score(training_data,Y_train)*100)
print("Predicted value for testing data:",a.score(testing_data,Y_test)*100)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 99.75319721785955
Predicted value for testing data: 98.9237668161435


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(Y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(Y_train,a.predict(training_data))
print(cm1)

confusion matrix for testing data
[[967   1]
 [ 11 136]]
confusion matrix for traning data
[[3857    0]
 [  11  589]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
b=KNeighborsClassifier()
b.fit(training_data,Y_train)
y_pred=b.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",b.score(training_data,Y_train)*100)
print("Predicted value for testing data:",b.score(testing_data,Y_test)*100)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 93.56069104778999
Predicted value for testing data: 92.37668161434978


In [ ]:
from sklearn.naive_bayes import MultinomialNB
c=MultinomialNB()
c.fit(training_data,Y_train)
y_pred=c.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",c.score(training_data,Y_train)*100)
print("Predicted value for testing data:",c.score(testing_data,Y_test)*100)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 99.23715503702041
Predicted value for testing data: 99.01345291479821


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.svm import SVC
d=SVC()
d.fit(training_data,Y_train)
y_pred=d.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",d.score(training_data,Y_train)*100)
print("Predicted value for testing data:",d.score(testing_data,Y_test)*100)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 99.50639443571909
Predicted value for testing data: 98.7443946188341


In [ ]:
from sklearn.tree import DecisionTreeClassifier
e=DecisionTreeClassifier()
e.fit(training_data,Y_train)
y_pred=e.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",e.score(training_data,Y_train)*100)
print("Predicted value for testing data:",e.score(testing_data,Y_test)*100)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 100.0
Predicted value for testing data: 97.21973094170404


In [ ]:
from sklearn.ensemble import RandomForestClassifier
f=RandomForestClassifier()
f.fit(training_data,Y_train)
y_pred=f.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))
print("Predicted value for training data:",f.score(training_data,Y_train)*100)
print("Predicted value for testing data:",f.score(testing_data,Y_test)*100)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Predicted value for training data: 100.0
Predicted value for testing data: 98.47533632286995
